/obj/machinery/vending/plushesmat
	name = "\improper Donksoft Plushes Vendor"
	desc = "Ages 8 and up approved vendor that dispenses toys."
	icon = 'modular_mankind/_storage_icons/icons/machinery/vending_plushes.dmi'
	icon_state = "plushesmat"
	product_slogans = "Get your cool toys today!"
	product_ads = "Feel tough with your toys!;Express your inner child today!"
	vend_reply = "Come back for more!"
	light_mask = "plushesmat-light-mask"
	circuit = /obj/item/circuitboard/machine/vending/plushesmat
	products = list(
		/obj/item/toy/plush/mankind/borbplushie = 3,
		/obj/item/toy/plush/mankind/deer = 3,
		/obj/item/toy/plush/mankind/fermis = 3,
		/obj/item/toy/plush/mankind/fermis/chen = 3,
		/obj/item/toy/plush/mankind/sechound = 3,
		/obj/item/toy/plush/mankind/medihound = 3,
		/obj/item/toy/plush/mankind/engihound = 3,
		/obj/item/toy/plush/mankind/scrubpuppy = 3,
		/obj/item/toy/plush/mankind/meddrake = 3,
		/obj/item/toy/plush/mankind/secdrake = 3,
		/obj/item/toy/plush/mankind/fox = 3,
		/obj/item/toy/plush/mankind/duffmoth = 3,
		/obj/item/toy/plush/mankind/leaplush = 3,
		/obj/item/toy/plush/mankind/sarmieplush = 3,
		/obj/item/toy/plush/mankind/sharknet = 3,
		/obj/item/toy/plush/mankind/pintaplush = 3,
		/obj/item/toy/plush/mankind/szaplush = 3,
		/obj/item/toy/plush/mankind/riffplush = 3,
		/obj/item/toy/plush/mankind/ian = 3,
		/obj/item/toy/plush/mankind/ian/small = 3,
		/obj/item/toy/plush/mankind/ian/lisa = 3,
		/obj/item/toy/plush/mankind/cat = 3,
		/obj/item/toy/plush/mankind/cat/tux = 3,
		/obj/item/toy/plush/mankind/cat/white = 3,
		/obj/item/toy/plush/mankind/seaduplush = 3,
		/obj/item/toy/plush/mankind/mechanic_fox = 3,
		/obj/item/toy/plush/mankind/tribal_salamander = 3,
		/obj/item/toy/plush/mankind/commanding_teshari = 3,
		/obj/item/toy/plush/mankind/breakdancing_bird = 3,
		/obj/item/toy/plush/mankind/skreking_vox = 3,
		/obj/item/toy/plush/mankind/blue_dog = 3,
		/obj/item/toy/plush/mankind/engi_snek = 3,
		/obj/item/toy/plush/mankind/glitch_synth = 3,
		/obj/item/toy/plush/mankind/boom_bird = 3,
		/obj/item/toy/plush/mankind/blue_cat = 3,
		/obj/item/toy/plush/mankind/igneous_synth = 3,
		/obj/item/toy/plush/mankind/edgy_bird = 3,
		/obj/item/toy/plush/mankind/tree_ferret = 3,
		/obj/item/toy/plush/mankind/fox/mia = 3,
		/obj/item/toy/plush/mankind/fox/kailyn = 3,
		/obj/item/toy/plush/mankind/xixi = 3,
		/obj/item/toy/plush/mankind/zapp = 3,
		/obj/item/toy/plush/mankind/rubi = 3,
		/obj/item/toy/plush/mankind/roselia = 3,
		/obj/item/toy/plush/mankind/chunko = 3,
		/obj/item/toy/plush/mankind/chunko/bonnie = 3,
		/obj/item/toy/plush/mankind/chunko/andrew = 3,
		/obj/item/toy/plush/mankind/chunko/inessa = 3,
		/obj/item/toy/plush/mankind/tesh = 3,
		/obj/item/toy/plush/mankind/immovable_rod = 3,
		/obj/item/toy/plush/mankind/voodoo = 3,
		/obj/item/toy/plush/mankind/plushie_winrow = 3,
		/obj/item/toy/plush/mankind/plushie_star = 3,
		/obj/item/toy/plush/mankind/plushie_chiara = 3,
		/obj/item/toy/plush/mankind/plushie_dan = 3,
		/obj/item/toy/plush/mankind/fox/plushie_jeanne = 3,
		/obj/item/toy/plush/mankind/plushie_azyre = 3,
		/obj/item/toy/plush/mankind/plushie_razurath = 3,
		/obj/item/toy/plush/mankind/plushie_razurath/second = 3,
		/obj/item/toy/plush/mankind/plushie_elofy = 3,
		/obj/item/toy/plush/mankind/plushie_syntax1112 = 3,
		/obj/item/toy/plush/mankind/snow_owl = 3,
		/obj/item/toy/plush/mankind/derg_plushie = 3,
		/obj/item/toy/plush/mankind/tracy = 3,
		/obj/item/toy/plush/mankind/plushie_synthia = 3,
		/obj/item/toy/plush/mankind/courier_synth = 3,
		/obj/item/toy/plush/mankind/plush_janiborg = 3,
		/obj/item/toy/plush/mankind/kotwithfunnyhat = 3,
		/obj/item/toy/plush/mankind/kotrazumist = 3,
		/obj/item/toy/plush/carpplushie/ice = 3,
		/obj/item/toy/plush/carpplushie/silent = 3,
		/obj/item/toy/plush/carpplushie/electric = 3,
		/obj/item/toy/plush/carpplushie/gold = 3,
		/obj/item/toy/plush/carpplushie/toxin = 3,
		/obj/item/toy/plush/carpplushie/dragon = 3,
		/obj/item/toy/plush/carpplushie/pink = 3,
		/obj/item/toy/plush/carpplushie/candy = 3,
		/obj/item/toy/plush/carpplushie/nebula = 3,
		/obj/item/toy/plush/carpplushie/void = 3,
		/obj/item/toy/plush/axolotlplushie = 3,
		/obj/item/toy/plush/mankind/shark = 3,
		/obj/item/toy/plush/mankind/pig = 3,
		/obj/item/toy/plush/mankind/toolbox = 3,
		/obj/item/toy/plush/mankind/shardplushie = 3,
		/obj/item/toy/plush/mankind/hampter = 3,
		/obj/item/toy/plush/mankind/hampter/asisstant = 3,
		/obj/item/toy/plush/mankind/hampter/security = 3,
		/obj/item/toy/plush/mankind/hampter/medic = 3,
		/obj/item/toy/plush/mankind/hampter/janitor = 3,
		/obj/item/toy/plush/mankind/hampter/captain = 3,
		/obj/item/toy/plush/mankind/hampter/captain/old = 3,
		/obj/item/toy/plush/mankind/hampter/syndi = 3,
		/obj/item/toy/plush/mankind/hampter/death_squad = 3,
		/obj/item/toy/plush/mankind/hampter/ert_squad = 3,)
	premium = list(
		/obj/item/toy/plush/landmine = 2,
		/obj/item/toy/plush/mankind/lizzyplush = 2,
		/obj/item/toy/plush/mankind/jecca = 2,
		/obj/item/toy/plush/mankind/beaver = 2,
		/obj/item/toy/plush/mankind/rd = 2,
		/obj/item/toy/plush/mankind/rimri = 2,
		/obj/item/toy/plush/mankind/rimri/snow = 2,
		/obj/item/toy/plush/mankind/kira = 2,
		/obj/item/toy/plush/mankind/mira = 2,
		/obj/item/toy/plush/mankind/tora = 2,
		/obj/item/toy/plush/mankind/miner = 2,
		/obj/item/toy/plush/mankind/mibib = 2,
		/obj/item/toy/plush/mankind/grogu = 2,
		/obj/item/toy/talking/neznakomka = 2,
		/obj/item/toy/talking/barmen_tim = 2,
		/obj/item/toy/plush/mankind/brigadier_general = 2,)
	contraband	= list(
		/obj/item/toy/plush/mankind/separ = 1,
		)
	armor = list("melee" = 20, "bullet" = 20, "laser" = 20, "energy" = 20, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 200, "acid" = 50)
	resistance_flags = FIRE_PROOF
	refill_canister = /obj/item/vending_refill/plushesmat
	default_price = 50
	extra_price = 200

/obj/item/vending_refill/plushesmat
	machine_name = "Donksoft Plushes Vendor"
	icon_state = "refill_donksoft"

/obj/item/circuitboard/machine/vending/plushesmat
	name = "Donksoft Plushes Vendor (Machine Board)"
	build_path = /obj/machinery/vending/plushesmat
	req_components = list(
		/obj/item/stack/sheet/glass = 1,
		/obj/item/vending_refill/plushesmat = 1)
