#define DNA_UNI_IDENTITY_BLOCKS 11

#define DNA_W_TTS_VOICES_SOUND_BLOCK		8
#define DNA_W_TTS_VOICES_SPEED_BLOCK		9
#define DNA_W_TTS_VOICES_PITCH_BLOCK		10
#define DNA_W_TTS_VOICES_VARIANCE_BLOCK		11
